blank_issues_enabled: false
contact_links:
  - name: WeChat
    url: http://admin.x-surge.com
    about: Ask questions and discuss with other Vben users in real time.
  - name: Questions & Discussions
    url: https://github.com/anncwb/vue-vben-admin/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
